-- ============================================================
-- NER SMART LOGISTICS PLATFORM
-- PostgreSQL + PostGIS Database Schema
-- ============================================================

-- Enable PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;

-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    role TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- DRIVERS
-- ============================================================

CREATE TABLE drivers (
    driver_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id),
    license_number TEXT,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- VEHICLES
-- ============================================================

CREATE TABLE vehicles (
    vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_number TEXT UNIQUE NOT NULL,
    driver_id BIGINT REFERENCES drivers(driver_id),
    vehicle_type TEXT,
    capacity_kg NUMERIC,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- VEHICLE LOCATIONS
-- ============================================================

CREATE TABLE vehicle_locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT REFERENCES vehicles(vehicle_id),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    location GEOGRAPHY(POINT, 4326),
    speed NUMERIC,
    heading NUMERIC,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- DISTRICTS
-- ============================================================

CREATE TABLE districts (
    district_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_name TEXT NOT NULL,
    state_name TEXT NOT NULL,
    geometry GEOGRAPHY(POLYGON, 4326),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ROADS
-- ============================================================

CREATE TABLE roads (
    road_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    road_name TEXT NOT NULL,
    road_type TEXT,
    condition TEXT DEFAULT 'UNKNOWN',
    accessibility_status TEXT DEFAULT 'ACCESSIBLE',
    geometry GEOGRAPHY(LINESTRING, 4326),
    speed_limit NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- BRIDGES
-- ============================================================

CREATE TABLE bridges (
    bridge_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bridge_name TEXT,
    condition TEXT,
    status TEXT DEFAULT 'OPERATIONAL',
    geometry GEOGRAPHY(POINT, 4326),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- SHIPMENTS
-- ============================================================

CREATE TABLE shipments (
    shipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_code TEXT UNIQUE NOT NULL,
    vehicle_id BIGINT REFERENCES vehicles(vehicle_id),
    cargo_type TEXT NOT NULL,
    origin TEXT NOT NULL,
    destination TEXT NOT NULL,
    priority TEXT DEFAULT 'NORMAL',
    status TEXT DEFAULT 'PENDING',
    expected_delivery TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- DELIVERIES
-- ============================================================

CREATE TABLE deliveries (
    delivery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT REFERENCES shipments(shipment_id),
    current_status TEXT,
    expected_eta TIMESTAMPTZ,
    actual_delivery_time TIMESTAMPTZ,
    delay_minutes INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- INCIDENTS
-- ============================================================

CREATE TABLE incidents (
    incident_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_type TEXT NOT NULL,
    description TEXT,
    severity TEXT NOT NULL,
    reported_by BIGINT REFERENCES users(user_id),
    location GEOGRAPHY(POINT, 4326),
    photo_url TEXT,
    status TEXT DEFAULT 'ACTIVE',
    reported_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- WEATHER DATA
-- ============================================================

CREATE TABLE weather_data (
    weather_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location GEOGRAPHY(POINT, 4326),
    temperature NUMERIC,
    rainfall_mm NUMERIC,
    humidity NUMERIC,
    wind_speed NUMERIC,
    weather_condition TEXT,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- HAZARD PREDICTIONS
-- ============================================================

CREATE TABLE hazard_predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location GEOGRAPHY(POINT, 4326),
    hazard_type TEXT NOT NULL,
    probability NUMERIC,
    risk_level TEXT,
    prediction_time TIMESTAMPTZ DEFAULT NOW(),
    valid_until TIMESTAMPTZ
);

-- ============================================================
-- ROUTES
-- ============================================================

CREATE TABLE routes (
    route_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT REFERENCES vehicles(vehicle_id),
    shipment_id BIGINT REFERENCES shipments(shipment_id),
    origin GEOGRAPHY(POINT, 4326),
    destination GEOGRAPHY(POINT, 4326),
    route_geometry GEOGRAPHY(LINESTRING, 4326),
    distance_km NUMERIC,
    estimated_time_minutes INTEGER,
    risk_score NUMERIC,
    route_status TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ACCESSIBILITY SCORES
-- ============================================================

CREATE TABLE accessibility_scores (
    accessibility_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id BIGINT REFERENCES districts(district_id),
    score NUMERIC,
    road_score NUMERIC,
    bridge_score NUMERIC,
    weather_score NUMERIC,
    hazard_score NUMERIC,
    traffic_score NUMERIC,
    status TEXT,
    calculated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ALERTS
-- ============================================================

CREATE TABLE alerts (
    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_type TEXT,
    title TEXT NOT NULL,
    message TEXT,
    severity TEXT,
    location GEOGRAPHY(POINT, 4326),
    vehicle_id BIGINT REFERENCES vehicles(vehicle_id),
    shipment_id BIGINT REFERENCES shipments(shipment_id),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);